name: Databricks Asset Bundle - CICD (UAT Only)

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10.12'

jobs:
  deploy-uat:
    runs-on: self-hosted   # <-- Ab yaha self-hosted runner
    name: Validate and Deploy Bundle to UAT
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          echo "$HOME/.databricks/bin" >> $GITHUB_PATH

      - name: Test Authentication (UAT with MI)
        env:
          DATABRICKS_HOST: https://adb-1375573820735468.8.azuredatabricks.net
          ARM_USE_MSI: true
          ARM_CLIENT_ID: ${{ secrets.DATABRICKS_MI_CLIENT_ID }}
        run: databricks workspace list /

      - name: Validate bundle (UAT)
        env:
          DATABRICKS_HOST: https://adb-1375573820735468.8.azuredatabricks.net
          ARM_USE_MSI: true
          ARM_CLIENT_ID: ${{ secrets.DATABRICKS_MI_CLIENT_ID }}
        run: databricks bundle validate --target uat

      - name: Deploy bundle (UAT)
        env:
          DATABRICKS_HOST: https://adb-1375573820735468.8.azuredatabricks.net
          ARM_USE_MSI: true
          ARM_CLIENT_ID: ${{ secrets.DATABRICKS_MI_CLIENT_ID }}
        run: databricks bundle deploy --target uat
